### ISSUE TITLE
Fails in very big repositories

### ISSUE THREAD

**Issue by IonicaBizau** [alessioalex/git-authors#1]
Honestly, I didn't test it, but I'm sure it will fail when the repository is big enough to make `exec` to send an error back.

The solution would be to parse things one by one. What do you think?

**Comment by alessioalex** [comment]
You are probably right, but for that to happen it would mean that a project should have thousand of contributors. I'll convert this to a stream when I have the time, thanks for the suggestion!

**Comment by IonicaBizau** [comment]
@alessioalex I can fix this. I need this library in `git-stats`. :smile:

**Comment by alessioalex** [comment]
@IonicaBizau thanks, help appreciated. You can see how I've done the streaming part for my other git libraries (I have a lot of them as I'm kind of creating my own Github with Node): https://github.com/search?q=user%3Aalessioalex+git
